language: node_js
node_js:
- lts/*
sudo: required
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
# install:
# - yarn global add codecov
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn install
- yarn test:ci
after_success:
- yarn build:ci
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ./dist/Portfolio
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master
